name: Firmware Extraction and Recovery Image Extraction

on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: 'URL of the firmware (e.g., a zip file or a payload.bin)'
        required: true
        default: 'https://example.com/path/to/firmware.zip'

jobs:
  extract_firmware_and_recovery_img:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install required dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y xz-utils unzip git
        wget https://dl.google.com/go/go1.19.6.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.19.6.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin

    # Clone the payload-dumper-go repository
    - name: Clone payload-dumper-go
      run: git clone https://github.com/ssut/payload-dumper-go.git

    # Build the payload-dumper-go binary
    - name: Build payload-dumper-go
      run: |
        cd payload-dumper-go
        go build -o payload-dumper-go .
        if [ ! -f "payload-dumper-go" ]; then
          echo "payload-dumper-go build failed"
          exit 1
        fi

    # Download the firmware archive or payload.bin from the given URL
    - name: Download firmware archive
      run: |
        wget -O firmware.zip ${{ github.event.inputs.firmware_url }}

    # Extract firmware archive (if it's a zip)
    - name: Extract firmware archive
      run: |
        if [[ "${{ github.event.inputs.firmware_url }}" == *.zip ]]; then
          unzip firmware.zip
        fi

    # Extract partitions from payload.bin if found in the firmware
    - name: Extract partitions from payload.bin
      run: |
        if [ -f "payload.bin" ]; then
          ./payload-dumper-go payload.bin
        fi

    # Extract other image files from the firmware (if present)
    - name: Extract images from archive
      run: |
        if [[ -f "firmware.zip" && ! -f "payload.bin" ]]; then
          mkdir extracted_images
          unzip firmware.zip -d extracted_images
        fi

    # Move recovery.img to output folder if it exists
    - name: Move recovery.img to output
      run: |
        mkdir -p output
        if [ -f "recovery.img" ]; then
          mv recovery.img output/
        fi

    # Download dat2img scripts
    - name: Download dat2img scripts
      run: |
        wget https://raw.githubusercontent.com/ShazuxD7/dat2img/master/sdat2img.py
        wget https://raw.githubusercontent.com/ShazuxD7/dat2img/master/vdat2img.py

    # Check for system.new.dat and system.new.dat.br and convert if found
    - name: Convert system images
      run: |
        if [ -f "system.new.dat" ] || [ -f "system.new.dat.br" ]; then
          if [ -f "system.new.dat.br" ]; then
            python3 vdat2img.py system.new.dat.br system.img
          fi
          if [ -f "system.new.dat" ]; then
            python3 sdat2img.py system.new.dat system.img
          fi
        else
          echo "system.new.dat or system.new.dat.br not found."
        fi

    # Upload recovery.img as an artifact
    - name: Upload recovery.img
      uses: actions/upload-artifact@v3
      with:
        name: recovery-img
        path: output/recovery.img

    # Upload other images as an artifact (optional)
    - name: Upload extracted images (optional)
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: extracted-images
        path: extracted_images/
